name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Set up maven settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [
              {
                "id": "github-shared-artifacts",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.SHARED_ARTIFACT_SECRET }}"
              }
            ]
      - name: Deploy to GitHub packages
        run: mvn deploy -DskipTests
        env:
          GH_PAT: ${{ secrets.SHARED_ARTIFACT_SECRET }}